App:
  version: 1.0.0
  Env: 
    - dev

log:
  level: debug
  file: 
    enable: true
    path: ./log/naive-admin.log

data:
  pgsql:
    enable: true
    host: 127.0.0.1
    port: 5432
    db: my_admin
    user: root
    password: 123456
  redis:
    enable: true
    host: redis
    port: 6379
    password: 123456
    db: 0
  mqtt:
    enable: false
    broker: 
    user: 
    password: 
  rabbitmq:
    enable: false
    broker: 
    user: 
    password: 

server:
  gin:
    enable: true
    host: 0.0.0.0
    port: 9527

