App:
  version: 1.0.0
  Env: 
    - dev

log:
  level: debug
  file: 
    enable: true
    path: ./log/naive-admin.log

data:
  pgsql:
    enable: true
    host: db
    port: 5432
    db: spim
    user: spidersens
    password: JL)vF^ap}nCtb6@09hC~
  redis:
    enable: true
    host: redis
    port: 6379
    password: Bwk81000970
    db: 0
  mqtt:
    enable: false
    broker: 
    user: 
    password: 
  rabbitmq:
    enable: false
    broker: 
    user: 
    password: 

server:
  gin:
    enable: true
    host: 0.0.0.0
    port: 31326

